# This is a basic workflow to help you get started with Actions

name: Firebog Block list

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "00 00 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Generate the block list of firebog tick list
        run: scripts/create_list.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-commit changed blocklist files
